#! /bin/sh

# 背景画像
nitrogen --restore

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# マウスのアイコン
xsetroot -cursor_name left_ptr

# CapsLockキー を Ctrlキー にする
setxkbmap -option ctrl:nocaps

# fcitx5 自動起動
fcitx5 &

# 解像度設定スクリプト
$HOME/.screenlayout/display.sh

# Polybar 起動スクリプト
$HOME/.config/polybar/launch.sh
#killall polybar
#polybar &

# 透過処理
picom &

