[window]
padding = { x = 5, y = 5}
dynamic_padding = true
opacity = 0.8

[font]
size = 12
normal = { family = "HackGen Console NF", style = "Regular" }
bold = { family = "HackGen Console NF", style = "Bold" }
